### ISSUE TITLE
Error: unknown flag: --url : failed to execute root command unknown flag: --url

### ISSUE THREAD

**Issue by Madhan-Sadasivam** [snapp-incubator/ghodrat#7]
Hi, Please help me with the below error. 

![image](https://user-images.githubusercontent.com/89195883/140460998-26af3452-7ebf-4b64-94f5-5c532c4f04cd.png)

Also please provide the command for .yml file based execution.

**Comment by 1995parham** [comment]
Right now we only have Janus and .yml based execution. you need to create the following YAML configuration:

```yml
logger:
  development: true
  encoding: "console"
  level: "info"

tracer:
  enabled: false
  host: "localhost"
  port: 6831
  sample-rate: 0.1

call-count: 5

client:
  audio-file-address: "./static/audio.ogg"
  connection:
    stun-server: "stun:stun.l.google.com:19302"
    rtp-codec:
      clock-rate: 48000
      channels: 2
      payload-type: 111

janus:
  address: "<URL>"
  max-late: 10
  sample-rate: 48000
```
